frontend/controllers/StationController.php
<?php
/*
* Copyright 2023 DactylGroup s.r.o.
*
* Licensed under the EUPL, Version 1.2 or – as soon they
will be approved by the European Commission - subsequent
versions of the EUPL (the "Licence");
* You may not use this work except in compliance with the
Licence.
* You may obtain a copy of the Licence at:
*
* https://joinup.ec.europa.eu/software/page/eupl5
*
* Unless required by applicable law or agreed to in
writing, software distributed under the Licence is
distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied.
* See the Licence for the specific language governing
permissions and limitations under the Licence.
*/
?>


<?php

namespace frontend\controllers;

use common\models\search\StationSearch;
use common\models\Station;
use common\models\Station52;
use common\models\Station58;
use common\models\StationFs;
use common\models\StationWigig;
use common\models\Thread;
use common\models\UserAlliance;
use dactylcore\core\db\ActiveRecord;
use dactylcore\log\LogManager;
use dactylcore\log\LogOperation;
use DateTime;
use frontend\widgets\FrontendController;
use modules\user\common\models\User;
use Yii;
use yii\data\ArrayDataProvider;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class StationController extends FrontendController
{
    public const STEP_1_NAME = 1;
    public const STEP_2_LOCATION = 2;
    public const STEP_3_PARAMS = 3;
    public const STEP_4_SUMMARY = 4;
    public const SCENARIO_DELETE = 99;
    public const SCENARIO_UNPUBLISH = 'unpublish';
    public const TYPE_WIGIG = 'wigig';
    public const TYPE_FS = 'fs';
    public const PARTNER_SESSION_KEY = 'partnerCheck';
    public const TYPE_52 = '52ghz';
    public const TYPE_58_AP = 'ap_58ghz';
    public const TYPE_58_TG = 'tg_58ghz';
    public static $viewsFs
        = [
            self::STEP_1_NAME => 'step1_name',
            self::STEP_2_LOCATION => 'step2_location',
            self::STEP_3_PARAMS => 'step3_parameters',
            self::STEP_4_SUMMARY => 'step4_summary',
        ];
    public static $viewsWigig
        = [
            self::STEP_1_NAME => 'step1_name',
            self::STEP_2_LOCATION => 'step2_location',
            self::STEP_3_PARAMS => 'step3_parameters',
            self::STEP_4_SUMMARY => 'step4_summary',
        ];
    public static $views58
        = [
            self::STEP_1_NAME => 'step1_info',
            self::STEP_2_LOCATION => 'step2_location',
            self::STEP_3_PARAMS => 'step3_parameters',
            self::STEP_4_SUMMARY => 'step4_summary',
        ];
    public static $views52
        = [
            self::STEP_1_NAME => 'step1_name',
            self::STEP_2_LOCATION => 'step2_location',
            self::STEP_3_PARAMS => 'step3_parameters',
            self::STEP_4_SUMMARY => 'step4_summary',
        ];
    protected $myStationsOnly = false;
    protected $type = self::TYPE_WIGIG;
    protected $canEdit;
    protected $model;
    protected $modelStation;
    protected $modelTypeStation;

    public function behaviors()
    {
        $protectedOperations = [
//            'update',
            'delete',
            'publish',
            'prolong-registration',
            'declaration',
            'declare',
            'contact-to-conflict-users',
        ];
        return \yii\helpers\ArrayHelper::merge(parent::behaviors(), [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => false,
                        'actions' => $protectedOperations,
                        'matchCallback' => function ($rule, $action) use ($protectedOperations)
                        {
                            $id = Station::deFormatId(Yii::$app->request->get('id'));
                            return in_array($action->id, $protectedOperations) && !$this->canEdit($id);
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' =>
                            [
                                'create-fs',
                                'create-wigig',
                                'wigig-pair-dropdown-data',
                            ],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => false,
                        'actions' =>
                            [
                                'create-fs',
                                'create-wigig',
                                'wigig-pair-dropdown-data',
                            ],
                        'roles' => ['?'],
                    ],

                    'default' => [
                        'allow' => true,
                    ],
                ],
            ],
        ]);
    }

    public function actionMyStations()
    {
        $this->myStationsOnly = true;
        return $this->actionStations();
    }

    protected function checkUnpublishedLimit()
    {
        return (StationSearch::countUnpublishedStations(Yii::$app->getUser()->id) >= c('MAX_WAITING_STATIONS'));
    }

    public function actionCreateFs()
    {
        if ($this->checkUnpublishedLimit()) {
            throw new ForbiddenHttpException();
        }
        return $this->actionStationFs(self::STEP_1_NAME);
    }

    public function actionCreateWigig()
    {
        if ($this->checkUnpublishedLimit()) {
            throw new ForbiddenHttpException();
        }
        return $this->actionStationWigig(self::STEP_1_NAME);
    }

    public function actionCreateAccessPoint()
    {
        if ($this->checkUnpublishedLimit()) {
            throw new ForbiddenHttpException();
        }
        return $this->actionStationAccessPoint(self::STEP_1_NAME);
    }

    public function actionCreateTollGate()
    {
        if ($this->checkUnpublishedLimit()) {
            throw new ForbiddenHttpException();
        }
        return $this->actionStationTollGate(self::STEP_1_NAME);
    }

    public function actionCreateStation52Ghz()
    {
        if ($this->checkUnpublishedLimit()) {
            throw new ForbiddenHttpException();
        }
        return $this->actionStation52(self::STEP_1_NAME);
    }

    protected function getStationTypeAction($modelStation, $step, $checkAjax = true)
    {

        switch ($modelStation->type) {
            case self::TYPE_FS:
                return $this->actionStationFs($step, $modelStation->id, $checkAjax);
            case self::TYPE_WIGIG:
                return $this->actionStationWigig($step, $modelStation->id, $checkAjax);
            case self::TYPE_58_AP:
                return $this->actionStationAccessPoint($step, $modelStation->id, $checkAjax);
            case self::TYPE_58_TG:
                return $this->actionStationTollGate($step, $modelStation->id, $checkAjax);
            case self::TYPE_52:
                return $this->actionStation52($step, $modelStation->id, $checkAjax);
            default:
                throw new Exception(_tF('Invalid station type', 'station'));
        }
    }

    public function actionEdit($id = null)
    {
        if (!userIsLogged()) {
            return $this->redirect(['dc-user/user/login']);
        }

        $modelStation = $this->getModel($id);

        if ($modelStation == null) {
            throw new NotFoundHttpException();
        }
        if (!$this->canEdit($id)) {
            throw new ForbiddenHttpException();
        }
        if ($modelStation->status == Station::STATUS_UNPUBLISHED) {
            $modelStation->moveToStatus(Station::STATUS_DRAFT);
        }

        $step = $modelStation->loadStationProgress();

        return $this->getStationTypeAction($modelStation, $step);
    }

    public function actionStepBack($id)
    {
        $modelStation = $this->getModel($id);

        if ($modelStation == null) {
            throw new NotFoundHttpException();
        }

        $step = $modelStation->loadStationProgress();
        if ($step > 1) {
            $step -= 1;
            $modelStation->storeStationProgress($step);
        }

        return $this->getStationTypeAction($modelStation, $step, false);
    }

    public function actionStation($id = null, $editFinished = false)
    {
        // TODO subheader content ?
        $this->view->showSubHeader = true;
        $this->view->subHeaderContent = $this->renderPartial('detail/partial/sub_header');

        $id = Station::deFormatId($id);
        $modelStation = $this->getModel($id);
        $this->type = $modelStation->type;

        if ($this->canSee($id)) {

            if ($modelStation->status == Station::STATUS_WAITING ||
                $modelStation->status == Station::STATUS_DRAFT ||
                $modelStation->status == Station::STATUS_UNPUBLISHED ||
                $editFinished) {
                return $this->actionEdit($id);
            }

            $bData = [];
            $id = Station::deFormatId($id);

            $dataModel = null;
            /**
             * @var $modelStation Station
             */
            $modelStation = null;

            switch ($this->type) {
                case self::TYPE_FS:
                    $dataModel = StationSearch::getModelsFs($id);
                    $modelStation = $dataModel->stationA;
                    break;
                case self::TYPE_WIGIG:
                case self::TYPE_58_AP:
                case self::TYPE_58_TG:
                case self::TYPE_52:
                    $dataModel = $this->getModel($id);
                    $modelStation = $dataModel;
                    break;
                default:
                    break;
            }

            $searchModel = new StationSearch();
            $filter = Yii::$app->request->queryParams;

            switch ($modelStation->type) {

frontend/views/station/station/52ghz/step1_name.php
<?php
/*
* Copyright 2023 DactylGroup s.r.o.
*
* Licensed under the EUPL, Version 1.2 or – as soon they
will be approved by the European Commission - subsequent
versions of the EUPL (the "Licence");
* You may not use this work except in compliance with the
Licence.
* You may obtain a copy of the Licence at:
*
* https://joinup.ec.europa.eu/software/page/eupl5
*
* Unless required by applicable law or agreed to in
writing, software distributed under the Licence is
distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied.
* See the Licence for the specific language governing
permissions and limitations under the Licence.
*/
?>


<?php

/**
 * @var $steps array
 * @var $modelStation \common\models\Station
 * @var $modelStationType \common\models\Station58
 * @var $hasChanged string
 */

use frontend\widgets\ActiveForm;
use frontend\widgets\dactylkit\DactylKit; ?>

<?php $form = ActiveForm::begin([
    'id' => 'station-form',
    'pjax' => true,
    'pjaxOptions' => [
        'enablePushState' => true,
        'enableReplaceState' => true,
    ],
    'options' => [
        'data-url' => $modelStation->id ? url(['station/edit', 'id' => $modelStation->id]) : '',
        'data-changed' => $hasChanged,
    ],
    'action' => url($modelStation->id ? ['station/edit', 'id' => $modelStation->id] : ['station/create-station-52-ghz'])
]) ?>
    <script>
        var urlToPush = $("form#station-form").data('url');
        var hasChanged = $("form#station-form").data('changed') + "";
        if (history.pushState && urlToPush) {
            history.pushState(null, null, urlToPush); // URL is now /inbox/N
        }

        needsToReload = needsToReload || (hasChanged === 'true');
    </script>
    <div id="station-form-pjax">
        <div class="livebox--station-registration">
            <?= $this->render('../partial/header', ['model' => $modelStation, 'saveExit' => false]) ?>
            <div class="livebox--station-registration--content">
                <?= DactylKit::progressBar(1, $steps) ?>
                <h6><?= _tF('What is station name', 'station') ?></h6>
                <?= $form->field($modelStation, 'name')->textInput(['maxlength' => true]) ?>
            </div>
            <?= $this->render('../partial/footer', [
                'prevUrl' => '',
                'nextBtnLabel' => _tF('continue', 'station'),
                'continueBtn' => true,
                'dirtyNextBtnLabel' => '',
            ]) ?>
        </div>
    </div>
<?php ActiveForm::end() ?>

frontend/views/station/station/52ghz/step2_location.php
<?php
/*
* Copyright 2023 DactylGroup s.r.o.
*
* Licensed under the EUPL, Version 1.2 or – as soon they
will be approved by the European Commission - subsequent
versions of the EUPL (the "Licence");
* You may not use this work except in compliance with the
Licence.
* You may obtain a copy of the Licence at:
*
* https://joinup.ec.europa.eu/software/page/eupl5
*
* Unless required by applicable law or agreed to in
writing, software distributed under the Licence is
distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied.
* See the Licence for the specific language governing
permissions and limitations under the Licence.
*/
?>


<?php

/**
 * @var $steps array
 * @var $modelStation \common\models\Station
 * @var $modelStationType \common\models\StationWigig
 * @var $hasChanged string
 */

use frontend\assets\map\AddStation52Asset;
use frontend\widgets\ActiveForm;
use frontend\widgets\dactylkit\DactylKit; ?>

<?php $form = ActiveForm::begin([
    'id' => 'station-form',
    'pjax' => true,
    'pjaxOptions' => [
        'enablePushState' => true,
        'enableReplaceState' => true,
    ],
    'options' => [
        'data-url' => url(['station/edit', 'id' => $modelStation->id]),
        'data-changed' => $hasChanged,
    ],
    'action' => url(['station/edit', 'id' => $modelStation->id]),
]);
AddStation52Asset::register($this);
?>
    <script>
        var urlToPush = $("form#station-form").data('url');
        var hasChanged = $("form#station-form").data('changed') + "";
        if (history.pushState && urlToPush) {
            history.pushState(null, null, urlToPush); // URL is now /inbox/N
        }

        needsToReload = needsToReload || (hasChanged === 'true');
    </script>
    <div class="livebox--station-registration">
        <?= $this->render('../partial/header', ['model' => $modelStation, 'saveExit' => false]) ?>
        <div class="livebox--station-registration--content" id="vueapp-52">
            <?= DactylKit::progressBar(2, $steps) ?>
            <h6><?= _tF('Where is the station located', 'station') ?></h6>
            <span class="livebox--station-registration--content__subheading"><?= _tF('Use map to select location or enter GPS coordinates',
                    'station') ?></span>
            <div class="row no-gutters livebox--station-registration--content__location-inputs">
                <div class="col-md-6">
                    <?= $form->field($modelStation, 'lat')->textInput([
                        'id' => 'location-lat',
                        'maxlength' => true,
                        'v-model' => 'locationLat',
                        '@keyup' => 'changePosition',
                        'class' => 'dangerous',]) ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($modelStation, 'lng')->textInput([
                        'id' => 'location-lng',
                        'maxlength' => true,
                        'v-model' => 'locationLng',
                        '@keyup' => 'changePosition',
                        'class' => 'dangerous',]) ?>
                </div>
            </div>
        </div>

      <div class="map-outer-box" style="width: 100%; height: 100%">
        <div id="map-52" style="width: 100%; height: 100%; min-height: 250px;"
             data-stationlink="<?= url(['station/station', 'id' => 0]) ?>">
          <div class="overlay52 mapOverlay">
            <div class="lds-grid">
              <div></div>
              <div></div>
              <div></div>
              <div></div>
              <div></div>
              <div></div>
              <div></div>
              <div></div>
              <div></div>
            </div>
          </div>
        </div>
      </div>

        <?= $this->render('../partial/footer', [
            'prevUrl' => url(['station/step-back', 'id' => $modelStation->id]),
            'nextBtnLabel' => _tF('continue', 'station'),
            'continueBtn' => true,
            'dirtyNextBtnLabel' => _tF('save and continue', 'station'),
        ]) ?>
    </div>
<?php if ($modelStation->isPublished()): ?>
    <script>initDirtyForms(true);</script>
<?php else: ?>
    <script>initDirtyForms(false);</script>
<?php endif; ?>
    <script>
        getAllFlashAlertMessages();
        if (window['initStation52']) {
            initStation52();
        }
    </script>
<?php ActiveForm::end() ?>

frontend/views/station/station/52ghz/step3_parameters.php
<?php
/*
* Copyright 2023 DactylGroup s.r.o.
*
* Licensed under the EUPL, Version 1.2 or – as soon they
will be approved by the European Commission - subsequent
versions of the EUPL (the "Licence");
* You may not use this work except in compliance with the
Licence.
* You may obtain a copy of the Licence at:
*
* https://joinup.ec.europa.eu/software/page/eupl5
*
* Unless required by applicable law or agreed to in
writing, software distributed under the Licence is
distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied.
* See the Licence for the specific language governing
permissions and limitations under the Licence.
*/
?>


<?php

/**
 * @var $steps array
 * @var $modelStation \common\models\Station
 * @var $modelStationType \common\models\StationWigig
 * @var $hasChanged string
 */

use frontend\assets\map\AddStation52Asset;
use frontend\widgets\ActiveForm;
use frontend\widgets\dactylkit\DactylKit;

?>

<?php \yii\widgets\PjaxAsset::register($this) ?>

<?php $form = ActiveForm::begin([
    'id' => 'station-form',
    'pjax' => true,
    'pjaxOptions' => [
        'enablePushState' => true,
        'enableReplaceState' => true,
    ],
    'options' => [
        'data-url' => url(['station/edit', 'id' => $modelStation->id]),
        'data-changed' => $hasChanged,
        'data-id' => $modelStation->id,
    ],
    'action' => url(['station/edit', 'id' => $modelStation->id]),
]);

AddStation52Asset::register($this);
?>
    <script>
        var urlToPush = $("form#station-form").data('url');
        var hasChanged = $("form#station-form").data('changed') + "";
        if (history.pushState && urlToPush) {
            history.pushState(null, null, urlToPush); // URL is now /inbox/N
        }

        needsToReload = needsToReload || (hasChanged === 'true');
    </script>
    <div class="livebox--station-registration">
        <?= $this->render('../partial/header', ['model' => $modelStation, 'saveExit' => true]) ?>
        <div class="livebox--station-registration--content">
            <?= DactylKit::progressBar(3, $steps) ?>
            <h6><?= $modelStation->getAttributeLabel('macAddress') ?></h6>
            <?= $form->field($modelStation, "macAddress")->textInput()->hint(false) ?>
        </div>
        <?= $this->render('../partial/footer', [
            'prevUrl' => url(['station/step-back', 'id' => $modelStation->id]),
            'nextBtnLabel' => _tF('save and continue', 'station'),
            'dirtyNextBtnLabel' => _tF('save and recount', 'station'),
            'continueBtn' => true,
        ]) ?>
    </div>
<?php if ($modelStation->isPublished()): ?>
    <script>initDirtyForms(true);</script>
<?php else: ?>
    <script>initDirtyForms(false);</script>
<?php endif; ?>

<?php ActiveForm::end() ?>

frontend/views/station/station/52ghz/step4_summary.php
<?php
/*
* Copyright 2023 DactylGroup s.r.o.
*
* Licensed under the EUPL, Version 1.2 or – as soon they
will be approved by the European Commission - subsequent
versions of the EUPL (the "Licence");
* You may not use this work except in compliance with the
Licence.
* You may obtain a copy of the Licence at:
*
* https://joinup.ec.europa.eu/software/page/eupl5
*
* Unless required by applicable law or agreed to in
writing, software distributed under the Licence is
distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied.
* See the Licence for the specific language governing
permissions and limitations under the Licence.
*/
?>


<?php

/**
 * @var $dataProvider
 * @var $searchModel
 * @var $model Station
 * @var $modelStation Station
 * @var $startedConversationsWith array
 * @var $bData array
 * @var $steps array
 * @var $hasChanged string
 * @var $anyInConflict boolean - is there any conflict with other stations
 */

use frontend\assets\map\CalcStation52Asset;
use common\models\Station;
use frontend\widgets\ActiveForm;
use frontend\widgets\dactylkit\DactylKit;

$model = $modelStation;

$modelLabels = $model->attributeLabels();

$progressStep = $modelStation->status == Station::STATUS_FINISHED ? 4 : 3;
if ($modelStation->isForProlongation()) {
    $nextBtnLabel = _tF('prolong station', 'station');
} else {
    $nextBtnLabel = $modelStation->status == Station::STATUS_FINISHED ? '' : _tF('publish', 'station');
}


?>

<?php $form = ActiveForm::begin([
    'id' => 'station-form',
    'pjax' => true,
    'pjaxOptions' => [
        'enablePushState' => true,
        'enableReplaceState' => true,
    ],
    'options' => [
        'data-url' => url(['station/edit', 'id' => $modelStation->id]),
        'data-changed' => (string)$hasChanged,
    ],
    'action' => url(['station/publish', 'id' => $modelStation->id]),
]);
CalcStation52Asset::register($this);
?>
<script>
    var urlToPush = $("form#station-form").data('url');
    var hasChanged = $("form#station-form").data('changed') + "";

    if (history.pushState && urlToPush) {
        history.pushState(null, null, urlToPush); // URL is now /inbox/N
    }
    needsToReload = needsToReload || (hasChanged === 'true');
</script>
<div class="livebox--station-registration">
    <?= $this->render('../partial/header', ['model' => $model, 'saveExit' => true]) ?>
    <div class="livebox--station-registration--content">
        <?= DactylKit::progressBar($progressStep, $steps) ?>
        <span class="dk--table--ghost__heading"><?= _tF('information', 'station') ?></span>
        <table class="dk--table dk--table--ghost">
            <tbody>
            <tr>
                <td><?= _tF('kind', 'station') ?></td>
                <td><?= $modelStation->getTypeShortCut() ?></td>
            </tr>
            <?php if ($modelStation->mac_address): ?>
                <tr>
                    <td><?= $modelLabels['mac_address'] ?></td>
                    <td><?= mb_strtoupper($modelStation->mac_address) ?></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <hr id="vueapp-52-calc" class="dk--hr">
        <span class="dk--table--ghost__heading"><?= _tF('location', 'station') ?></span>
        <table class="dk--table dk--table--ghost">
            <tbody>
            <tr>
                <td><?= _tF('GPS', 'station') ?></td>
                <td><?= "{$model->lng}°, {$model->lat}°" ?></td>
            </tr>
            </tbody>
        </table>
        <div style="width: 100%; height: 400px">
            <div id="map-calc-52" style="width: 100%; height: 100%;  min-height: 250px;"
                 data-stationlink="<?= url(['station/station', 'id' => 0]) ?>">
                <div class="mapOverlay overlayCalc52">
                    <div class="lds-grid">
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?= $this->render('../partial/footer', [
        'prevUrl' => url(['station/step-back', 'id' => $modelStation->id]),
        'nextBtnLabel' => $nextBtnLabel,
        'dirtyNextBtnLabel' => '',
        'continueBtn' => false,
    ]) ?>
</div>
<script>
    getAllFlashAlertMessages();
    if (window['initStationCalc52']) {
        initStationCalc52();
    }
</script>
<?php ActiveForm::end() ?>